# run: Main.class
# 	java Main
#
# Main.class: Main.java Screen.class
# 	javac Main.java

# run: PenroseTriangle.class
# 	java PenroseTriangle
#
# Main.class: PenroseTriangle.java Screen.class
# 	javac PenroseTriangle.java

run: Main.class
	java Main

Main.class: Main.java Screen.class
	javac Main.java

Screen.class: Screen.java
	javac Screen.java

clean:
	rm *.class
